### ISSUE TITLE
Hours not displayed

### ISSUE THREAD

**Issue by oceanlazy** [kivy-garden/garden.circulardatetimepicker#9]
After `python __init__.py`
[screenshot](https://imgur.com/a/5cMTZTP)
```
[INFO   ] [Logger      ] Record log in /home/v/.kivy/logs/kivy_19-01-31_58.txt
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <b'3.0 Mesa 18.0.5'>
[INFO   ] [GL          ] OpenGL vendor <b'VMware, Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'SVGA3D; build: RELEASE;  LLVM;'>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <b'1.30'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Exception ignored in: 'kivy.graphics.instructions.RenderContext.set_texture'
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Exception ignored in: 'kivy.graphics.instructions.RenderContext.set_texture'
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Exception ignored in: 'kivy.graphics.instructions.RenderContext.set_texture'
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Exception ignored in: 'kivy.graphics.instructions.RenderContext.set_texture'
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Exception ignored in: 'kivy.graphics.instructions.RenderContext.set_texture'
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Exception ignored in: 'kivy.graphics.instructions.RenderContext.set_texture'
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Exception ignored in: 'kivy.graphics.instructions.RenderContext.set_texture'
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Exception ignored in: 'kivy.graphics.instructions.RenderContext.set_texture'
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Exception ignored in: 'kivy.graphics.instructions.RenderContext.set_texture'
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Exception ignored in: 'kivy.graphics.instructions.RenderContext.set_texture'
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Exception ignored in: 'kivy.graphics.instructions.RenderContext.set_texture'
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
 Exception ignored in: 'kivy.graphics.instructions.RenderContext.set_texture'
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 789, in kivy.graphics.texture.Texture.bind
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 662, in _texture_fill
     self.render(real=True)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 603, in render
     return self._render_real()
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 586, in _render_real
     self.render_lines(lines, options, self._render_text, y, size)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/__init__.py", line 564, in render_lines
     render_text(line, x, y)
   File "/home/v/PycharmProjects/test/venv/lib/python3.6/site-packages/kivy/core/text/text_sdl2.py", line 48, in _render_text
     self._surface.render(self, text, x, y)
   File "kivy/core/text/_text_sdl2.pyx", line 127, in kivy.core.text._text_sdl2._SurfaceContainer.render
 IndexError: list index out of range
```

**Comment by GuillaumeLam** [comment]
#10 Fixes this issue!

**Comment by ok-coder1** [comment]
Please close.
